#!/usr/bin/env bash
# One-time setup for the Wazuh single-node stack.
#
#   1. clones the pinned upstream wazuh-docker release
#   2. writes a .env of generated credentials (if absent)
#   3. relabels the config tree for SELinux
#   4. generates the indexer TLS certificates
#
# Idempotent: safe to re-run. Existing clones, .env files and certificates are
# left alone.

source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

cd "$REPO_ROOT"

# --- 1. upstream ------------------------------------------------------------
if [[ -d "$WAZUH_DIR" ]]; then
  log "Upstream already present at wazuh/wazuh-docker (skipping clone)"
else
  log "Cloning wazuh-docker $WAZUH_TAG"
  git clone --depth 1 --branch "$WAZUH_TAG" "$WAZUH_UPSTREAM" wazuh/wazuh-docker
  # Drop the nested .git: this is a vendored, disposable copy, not a submodule.
  rm -rf wazuh/wazuh-docker/.git
fi

# --- 2. credentials ---------------------------------------------------------
# gen_pw lives in _common.sh; MISP's bootstrap uses it too.
if [[ -f "$ENV_FILE" ]]; then
  log ".env already exists (leaving credentials untouched)"
else
  log "Generating credentials into .env"
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/wazuh-bootstrap.sh on $(date -Iseconds)
# This file is gitignored. See .env.example for the documented key list.

# Indexer 'admin' superuser. Also used by the manager and dashboard to connect.
INDEXER_PASSWORD=$(gen_pw)

# Internal 'kibanaserver' account the dashboard uses to talk to the indexer.
DASHBOARD_PASSWORD=$(gen_pw)

# Wazuh manager API account 'wazuh-wui'.
API_PASSWORD=$(gen_pw)
EOF
  chmod 600 "$ENV_FILE"
fi

# --- 3. SELinux -------------------------------------------------------------
relabel_config

# --- 4. certificates --------------------------------------------------------
# Presence of the directory is the marker, not a file inside it: the generator
# leaves this directory root-owned and mode 0500, so an unprivileged user
# cannot traverse it. It does not exist at all in a fresh clone, so this is
# still a reliable "have the certs been generated?" test.
CERT_DIR="$WAZUH_DIR/config/wazuh_indexer_ssl_certs"
if [[ -d "$CERT_DIR" ]]; then
  log "Certificates already generated (skipping)"
else
  log "Generating indexer TLS certificates"
  # Note the ordering: relabel_config above runs BEFORE this. The certificates
  # are written by a container into the bind-mounted config tree, and SELinux
  # gives new files the type of their parent directory — so having relabelled
  # the parent first, the certs come out as container_file_t already. There is
  # deliberately no relabel afterwards: the generator chowns this directory to
  # uid 999/1000, which would make an unprivileged chcon fail noisily for no
  # reason. Verify with scripts/wazuh-check.sh.
  docker_run docker compose \
    -f "$WAZUH_DIR/generate-indexer-certs.yml" \
    run --rm generator

  # The generator image logs "find: command not found" near the end. It is an
  # upstream bug in wazuh-certs-tool.sh (busybox image without findutils) and
  # is harmless — all twelve certificates are still produced and permissioned.
fi

log "Bootstrap complete. Next: scripts/wazuh-up.sh"
